### ISSUE TITLE
Typo in 4.5.3

### ISSUE THREAD

**Issue by gregrs-uk** [OpenIntroStat/ims#10]
https://github.com/OpenIntroOrg/randomization-and-simulation/blob/c3d7a2214c1ec5b118e9e5022bdba37ad59deb6c/04/TeX/04-V01.tex#L1306

> I’ve heard a technique called the percentile bootstrap that is very robust.

should perhaps read

> I’ve heard that a technique called the percentile bootstrap is very robust.

**Comment by mine-cetinkaya-rundel** [comment]
We rephrased this entirely, thanks for the report nonetheless!
