### ISSUE TITLE
child labor

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#103]
Frannie and her friend both went through the printed version carefully.  Here is what they found:

- [x] page 23, Exercise #1 (section 1.4) - table goes past the margins
- [x] page 178, Figure 10.1 is cut off (right edge)
- [x] page 183, footnote 2 & 3 are written on top of one another
- [x] page 205 (and i think the table repeats elsewhere), table 12.6 & 13.2 & 14.2 & 16.1, the rows should be spaced out more
- [x] page 227, footnote for guided practice with three parts, would be better not to have a blank line for parts (a) (b) (c)
- [x] page 229, same footnote issue with parts (a) and (b)
- [x] page 232, the figure is ginormous (right above "always draw a picture first")
- [x] page 238, footnote issue with (a) and (b)
- [x] page 239, figure 14.10, the caption is cutoff, also the density doesn't fit the histogram
- [x] page 243, footnote is written on top of itself
- [x] page 263, fig 16.1, the reference is messed up in the figure caption
- [x] page 325, table 20.1  (1) LaTeX symbols are messed up, (2) table runs off margin
- [x] page 336, exercise 17 (section 20.4), LaTeX symbols are messed up
- [x] page 344, figure 21.6, the ylim is set to be way too big
- [x] page 374, figure 23.1, legend (or caption explanation) for symbol / color differentiation?
- [x] page 374, table 23.2 goes past the margin
- [x] page 387, table 24.1. goes past the margin, but also has a ton of LaTeX problems.
- [x] page 388, table 24.2. goes past the margin, but also has a ton of LaTeX problems
- [x] page 409, figure 25.16, can't see the residual plots at all
- [x] page 424, figure 26.7, the figure is ginormous
- [x] page 438, solution to problem 2 in chapter 5, the figure is too tiny and also goes off the page
- [ ] solutions:  is there any easy way to change the format of all the variables from italic to tttype?
- [x] all of chapter 25: the top of the page is problematic.  the chapter title merges into the page number
- [x] all of chapter 26: the top of the page is problematic.  the chapter title merges into the page number

**Comment by mine-cetinkaya-rundel** [comment]
There isn't a super-easy way of changing variable names to tttype in the short answers. I'll track that at #104
