### ISSUE TITLE
Figure out indexing

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#12]
In v1 we use `\term{}` which is defined in `extraTeX/style`, but for now in v2 I'm using `index{}` as per https://bookdown.org/yihui/bookdown/latex-index.html. Need to make sure everything works in PDF version.

**Comment by beanumber** [comment]
We are handling this by writing a function like:

```
index <- function(index_label = "subject", x) {
  paste0("\\", "index{", index_label, ",", x, "}")
}
```

and then in the text you'd write: 

```
Mine is a brilliant `r index("data scientist")`. 
```

In general, converting all of your LaTeX macros to R functions gives you flexibility to change things later on. 

If you have a better solution I'm all :ear: !

**Comment by mine-cetinkaya-rundel** [comment]
Thanks @beanumber, that's a good idea! I'll try it here.

We had some complicated stuff going on with indexes, see https://github.com/OpenIntroStat/randomization-and-simulation/blob/612be65fc28266aca508ffae70c49f8ca899f389/extraTeX/style/style.tex#L184-L191, so I need to figure out if we need to replicate the whole thing or if we can trim it down a bit.
