### ISSUE TITLE
infer / pairing

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#144]
infer (as of June 2021) does not do a randomization test in the way that IMS describes.  instead, infer uses the differences and then does a bootstrap test for mu = 0.  i find the bootstrap test to be particularly complicated for students, and additionally, there is no reason for the computational method to be different from what is described in the text.  

For V2 the following need to be changed (hopefully with an update to infer!):
- chapter 21 (throughout)
- chapter 21 exercises
- chapter 23 case study

**Comment by mine-cetinkaya-rundel** [comment]
See https://github.com/tidymodels/infer/issues/215 for relevant issue on infer.

**Comment by hardin47** [comment]
ask simon.  or we could make a PR ourselves.  seems like at this point they aren't planning to implement.

**Comment by hardin47** [comment]
[issue](https://github.com/tidymodels/infer/issues/487#issue-1635751463) on the infer repo

**Comment by mine-cetinkaya-rundel** [comment]
This is addressed with #367.
