### ISSUE TITLE
Bibliography / References

### ISSUE THREAD

**Issue by espinielli** [OpenIntroStat/ims#148]
Great book(down), I am learning (stats) and meta-learning (from your Rmd/bookdown/LaTeX): Thanks.

A few points about Bibliography/References:
1. From the comments in the `ims-style.tex` file it looks like you would like to change "Bibliography" to "References".
    See [this StackExchange](https://tex.stackexchange.com/a/12598).
    It looks like that for your case it would be enough to have 
    ```LaTeX
    \renewcommand{\bibname}{References}
    ```
1. in the web version `References` is in the TOC but not in the PDF (at least in the sample).
    Maybe [this StackExchange](https://tex.stackexchange.com/a/8459) could help.

1. I would have `References` unnumbered (in the web version it is Appendix B), i.e. `# References {-}`

**Comment by mine-cetinkaya-rundel** [comment]
This seems to all be implemented now. Thanks for the feedback!
