### ISSUE TITLE
Annotating Quarto books

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#15]
This is very cool: https://github.com/benmarwick/bookdown-ort 

Just leaving here to not lose track

**Comment by hardin47** [comment]
the book succinctly describes the basic things one might want to do with bookdown.  seems like we've moved past this now?  and less related with the move to quarto?

**Comment by mine-cetinkaya-rundel** [comment]
There's a built-in option for quarto too: https://quarto.org/docs/reference/projects/websites.html#comments. Probably worth keeping on the radar, I've heard good things about using these for teaching.
