### ISSUE TITLE
p. 36, Chapter 2 - Four sampling methods

### ISSUE THREAD

**Issue by IZE85** [OpenIntroStat/ims#152]
"For example, if neighborhoods represented clusters, then cluster or multistage sampling work best when the neighborhoods are very diverse."

I find this sentence slightly counterintuitive to what was said before. The sentence would make more sense to me, if it was more specific on what actually has to be diverse. Just as an example, the following would have been more clear to me:

"For example, if neighborhoods represented clusters, then cluster or multistage sampling work best when the housing units within each neighborhood are very diverse.", 

as each neighborhood to the next should be rather similar. I hope, I got the concept right in the first place.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you. This is addressed in d38298069480140e3177560e9586a770a9fbea36.
