### ISSUE TITLE
p. 49 Exercise 2.19, Exercise text

### ISSUE THREAD

**Issue by IZE85** [OpenIntroStat/ims#160]
The exercise text says, "The **_researcher_** believes that light levels might have different effects on people who wear glasses and people who don’t, so **_they_** want to make sure both groups of people are equally represented in each treatment."

In the beginning of the sentence it is only a single researcher (singular), while later on the text says that "they" (plural) want to make sure of something. Maybe this is ok in the English language, i am not an English native speaker so I cannot 100% say whether it's right or wrong.

**Comment by mine-cetinkaya-rundel** [comment]
It is ok to use "they" to not indicate gender (with he/she). That's something we tried to keep throughout the book. Thank you!
