### ISSUE TITLE
p. 87 one "space" before comma too much

### ISSUE THREAD

**Issue by IZE85** [OpenIntroStat/ims#165]
In the sentence

"The two boundaries of the box are called the first quartile (the 25th percentile, i.e., 25% of the data fall below this value) and the third quartile (the 75th percentile, i.e., 75% of the data fall below this value) , and these are often labeled Q1 and Q3, respectively."

there is one "blank space" after "[...] value)" too much

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
