### ISSUE TITLE
Chapter 8 p.153 problem with understanding of "source verified" vs. "verified"

### ISSUE THREAD

**Issue by IZE85** [OpenIntroStat/ims#176]
I have two remarks on this.

1. Maybe my misunderstanding builds on the parsimonious description of the "verified_income" variable in Table 8.2. My understanding would be: If source **_only_** is verified = "Source Verified", if **_both_** source **_and_** amount are verified = "Verified", otherwise "Not Verified".

If my understanding of the level interpretation of this variable is correct, then I do not get the text in the second example on page 153 that says:
"Using the model for predicting interest rate from income verification type, compute the average interest rate for borrowers whose income source and amount are both source verified."

Here, it says, "income source and amount are both source verified". Shouldn't it just be "income source is source verified"?

2. In the "Guided Practice" box on page 153 at the end of the text "Compute the average interest rate for borrowers whose income source and amount are both verified.1", I assume for consistency "verified" should be in italic as the other levels of the variable in the previous "example" boxes.

**Comment by hardin47** [comment]
fixed, thank you!!
