### ISSUE TITLE
p. 158 Typo in Footnote 8 + Footnote 7 remark

### ISSUE THREAD

**Issue by IZE85** [OpenIntroStat/ims#179]
1. Footnote 8: a zero for the "10,000" value in the denominator is missing, as n = 10,000.

2. Should Footnote 7 come one page before, as it was announced on page 157 (Guided Practice at the end of page 157) rather than on page 158?

**Comment by hardin47** [comment]
i fixed #1.  i don't know about #2.

**Comment by mine-cetinkaya-rundel** [comment]
I'll try to fix 2 when generating the PDF.
