### ISSUE TITLE
p. 157 Question regarding Guided Practice

### ISSUE THREAD

**Issue by IZE85** [OpenIntroStat/ims#180]
The text in the box says "The estimated value of the intercept is 1.925, and one might be tempted to make some interpretation of this coefficient, such as, it is the model’s predicted price when each of the variables take value zero: ..."

1. I am not able to find out, where this intercept estimate of "1.925" comes from.
2. ".... model's predicted price" - as our outcome variable is an "interest rate", wouldn't be "predicted interest rate" be a better wording?

**Comment by mine-cetinkaya-rundel** [comment]
Agreed, it should say 1.89. Thanks!
