### ISSUE TITLE
p. 188 dummy "cooling" vs. "coolingother"

### ISSUE THREAD

**Issue by IZE85** [OpenIntroStat/ims#188]
I think, it is rather misleading that the "cooling" variable is not used as intended by the text on page 188 and Table 10.4. In the text, it seems like "no cooling" is the baseline model. In the regression output the estimated coefficient of "coolingother" is negative, showing that the baseline model is now homes **_WITH_** central air conditioning.

This is confusing as in the "Example" box at the bottom of page 188 and in the "Guided Practice" box on page 189 the coefficient is now positive, contrary to what is listed in the regression output in Table 10.4.

**Comment by hardin47** [comment]
i think they are referring to the examples and guided practices on pgs 188 and 189.  should we change them to cooling_other?  or should we force `lm()` to use central as the baseline?

**Comment by mine-cetinkaya-rundel** [comment]
`coolingother` should be the baseline. This matches what's in the Example text and what's currently in HTML, but not in PDF. Make sure the same baseline level is used throughout the chapter.

**Comment by hardin47** [comment]
most of it was right in the HTML version.  there were a few places where b0 was hard coded incorrectly.  i *think* everything is now fixed (including the two GPs).  

after the pdf compiles, we should double check that the html and pdf match.
