### ISSUE TITLE
Chapter One Review

### ISSUE THREAD

**Issue by atheobold** [OpenIntroStat/ims#20]
- [X] Yes, acknowledge me in the book.

## Chapter One - Introduction to Data
- Generally, throughout the chapter there are extra spaces after using the typewriter text font to denote R syntax. 

### Relationships between variables (1.2.3)
In Figure 1.3, I think it would be great to choose a data point (county) on the plot, so that you could use a name label. This would make it consistent with how the county was labeled in Figure 1.2.

### Four sampling methods (1.3.5)
The items using the \term{} command are not appearing in the rendered HTML: strata and double-blind

### Introducing observational studies and experiments (1.2.5)
Stating that observational studies cannot (by themselves) show a causal connection may leave a student to wonder “Why?”. I would propose introducing the idea of confounding variables here, in a single sentence. It can then be stated that these ideas will be explored more later in section 1.3.4. 

### Principles of experimental design (1.4.1)
If the authors feel that it would be useful to the audience, I think adding a few sentences discussing the differences between replication and pseudo-replication could be a great addition. 

### Dataframes in R (1.5.1)
The example uses the `email50` dataset, which was not used previously in the chapter. Because the first column renders quite messily, I think using one of the datasets used previously may be less overwhelming when introducing what `R` output looks like.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you! All but pseudo-replication now addressed, and that's recorded at #32 for review later.
