### ISSUE TITLE
p. 210 wrong wording?

### ISSUE THREAD

**Issue by IZE85** [OpenIntroStat/ims#200]
On page 210 in Table 11.6 there is this (for me) rather strangely worded sentence: "What is the random process described?"

I am not a native speaker, so maybe that is the way it is supposed to be written.

**Comment by mine-cetinkaya-rundel** [comment]
For the simulation methods described we talk about random sampling and assignment. So this question is meant to be a prompt to describe what we mean by the random process in the given simulation scheme.

I'll close this for now as I can't think of better wording, but thank you for all the typo/clarification suggestions!

**Comment by IZE85** [comment]
oh, now i understand. just a suggestion: "What type is the random process described?"

**Comment by mine-cetinkaya-rundel** [comment]
That wording might suggest there are certain types to choose out of while the answers to the question don't come from a limited set of predefined options.
