### ISSUE TITLE
p. 221 and p. 223 Figure 12.3 and Figure 12.5 arrow and annotation need shift to the right

### ISSUE THREAD

**Issue by IZE85** [OpenIntroStat/ims#201]
I believe that the annotation and the arrow for "Bootstrap 2" and "Bootstrap k" in the dotplot in the right hand part of Figure 12.3 on page 221 (and also Figure 12.5 on page 223) that shows the distribution of the bootstraped samples for the medical consultant data, should be shifted one position to the right, as 

Resample 2: 4/7 = 0.57
Resample k: 5/7 = 0.71

while "Bootstrap 2" in your Figures marks at around 0.43 and "Bootstrap k" marks at 0.57.

**Comment by IZE85** [comment]
if i'm correct, this issues appears also on page 227 in Figure 12.8.

**Comment by hardin47** [comment]
done
