### ISSUE TITLE
Chapter review - Chapter 7 missing simulated_scatter

### ISSUE THREAD

**Issue by monika76five** [OpenIntroStat/ims#214]
Please use this template for providing chapter level feedback. For typos and grammatical corrections, feel free to list them here or make a pull request. For larger proposed edits (e.g. restructure how a topic is introduced, heavy edits, reordering, complete overhaul of a section, etc.) please use the issue form below instead of making a pull request.

Please feel free to keep comments brief. We would much prefer to follow up with you for clarification than have you spend time providing in depth suggestions for topics we have decided are outside of the scope of the book or edits that we think would change the style of the substantively.

Finally, we would like to thank you for your feedback in the [Acknowledgement](https://openintro-ims.netlify.app/index.html#acknowledgements) section of the book. Please check the boxes for if/how you would like to be acknowledged.

- [ ] Yes, acknowledge me in the book.
- [ ] Use my name in the acknowledgement. (Name: ____)
- [x] Link to my GitHub profile in the acknowledgement.
- [ ] Link to another profile / personal website in the acknowledgement. (Link: ____)
- [ ] Don't link to anything in the acknowledgement.

Please note that this project is released with a [Contributor Code of Conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/). By participating in this project you agree to abide by its terms.

Happy reviewing, and thank you so much for your comments! :heart:

---

### Section title Fitting a line to data

I am not sure if I missed it somewhere, but on line 28, "simulated_scatter" is called and I couldn't find how it was generated. It applies to not only this section but later sections as well.

...

**Comment by mine-cetinkaya-rundel** [comment]
The dataset comes from the openintro package: http://openintrostat.github.io/openintro/reference/simulated_scatter.html

We have a variety of simulated datasets stored in the package that we use for illustrating concepts: http://openintrostat.github.io/openintro/reference/index.html#section-simulated-datasets

**Comment by monika76five** [comment]
Thanks!
