### ISSUE TITLE
county data set missing in openintro package

### ISSUE THREAD

**Issue by staceyhancock** [OpenIntroStat/ims#22]
The county data set in Table 1.5 of Chapter 1 seems to be missing from the openintro package and repo.

**Comment by mine-cetinkaya-rundel** [comment]
@staceyhancock It's not missing actually, it's moved to https://github.com/OpenIntroStat/usdata (which is in the process of CRAN submission, should be on shortly) at which point openintro package will be resubmitted to CRAN with this dependency.

The goal is to ultimately have a seamless experience where you load openintro and you get everything, but the package size was creating an obstacle for getting it on CRAN so I'm trying this approach.

We hope to have this resolved when both packages make it on CRAN, I'm actively working on it.

**Comment by staceyhancock** [comment]
Great! Thanks, @mine-cetinkaya-rundel!

**Comment by mine-cetinkaya-rundel** [comment]
@staceyhancock All of this should be working now when you install openintro from CRAN
