### ISSUE TITLE
typos from Jeff Witmer

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#226]
Typos and other errors in IMS (compiled by Jeff Witmer)

- [x] 1. Exercise 1.9: Add a comma in "the fine leaves everything else unchanged, by instituting"
For the answers, (c) correctly gives "number of late pickups" as the response variable; but this is included in (d) also.

- [ ] 2. Solutions manual numbering of exercises is off in Chapter 12.

- [x] 3. This is not an error, but I greatly dislike the use of "n ≥ 30" as a criterion for appealing to the CLT. Also, the use of the wording "then we typically assume" on page 360, as this implies we can just make an assumption. Other wording could be "...then we require a nearly normal population..." Likewise in the next paragraph, we don't typically assume near normality, we infer it as a consequence of the CLT. (But thank you for writing about the "normality condition" rather than "normality assumption.")

- [x] 4. This is not an error, but I strongly prefer using Y, not X, as the generic univariate variable. We use Y for the response in regression, e.g., GPA ~ SAT; let's do the same when we have no predictor.

- [x] 5. Page 387:  "nn  =100 and ns =50" should be 867 and 113.

- [x] 6. Exercise 20.5: In part (a) we look at the middle 95%, then in part (b) we have to estimate the SD, which would mean looking at the middle 95% again. I suggest giving the reader the SD (SE) as being 5 and then asking for the CI in part (b).

- [x] 7. Exercises in Chpt 16 often show things like "1,000 parametric bootstrapped proportions, p=0.55" and I've had at least one student confused by the "p=0.55," thinking that was maybe a p-value.

- [x] 8. The end-of-the-book solution to exercise 20.9 is wrong (but the solutions manual has the right answer).

- [x] 9. The solutions manual solution to exercise 20.14 is wrong due to a typo: 57.1 should be 52.1.

**Comment by mine-cetinkaya-rundel** [comment]
For item 2 -- Adjust the language so 30 isn't the only deciding factor. See 23.2.2 for an example.

<img width="707" alt="Screen Shot 2021-12-13 at 11 52 31 AM" src="https://user-images.githubusercontent.com/5965649/145854423-16c3e07e-42a7-41e1-99fd-9febc83b4c84.png">

**Comment by mine-cetinkaya-rundel** [comment]
Item 4 sounds reasonable but we won't address that here, so checking the box.

**Comment by mine-cetinkaya-rundel** [comment]
Item 5 -- Give SD for 20.5, not for 20.6 since it asks for 90% CI (and you use 95% to guesstimate the SD).

**Comment by mine-cetinkaya-rundel** [comment]
Item 7 -- No update to how population proportion is denoted, but make sure we never say p or p-val for p-value

**Comment by mine-cetinkaya-rundel** [comment]
item 2 to be fixed in (private) solutions repo
