### ISSUE TITLE
Add alt text to remaining figures

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#234]
This has already been partially done but we still have more figures we need to add alt text for

**Comment by hardin47** [comment]
alt text is mostly done for the imported pictures.  it is not done for any ggplot figures or tables.  as we go through, i've given us a check list below to keep track of which chapters have been fixed.

- [ ] chp1
- [ ] chp2
- [ ] chp3
- [ ] chp4
- [ ] chp5
- [ ] chp6
- [ ] chp7
- [ ] chp8
- [ ] chp9
- [ ] chp10
- [ ] chp11
- [ ] chp12
- [ ] chp13
- [ ] chp14
- [ ] chp15
- [ ] chp16
- [ ] chp17
- [ ] chp18
- [ ] chp19
- [ ] chp20
- [ ] chp21
- [ ] chp22
- [ ] chp23
- [ ] chp24
- [ ] chp25
- [ ] chp26
- [ ] chp27

**Comment by hardin47** [comment]
TidyTuesday:

The DataViz Society/Nightingale by way of Amy Cesal has an [article](https://medium.com/nightingale/writing-alt-text-for-data-visualization-2a218ef43f81) on writing _good_ alt text for plots/graphs.

> Here’s a simple formula for writing alt text for data visualization:
> ### Chart type
> It’s helpful for people with partial sight to know what chart type it is and gives context for understanding the rest of the visual.
> Example: Line graph
> ### Type of data
> What data is included in the chart? The x and y axis labels may help you figure this out.
> Example: number of bananas sold per day in the last year
> ### Reason for including the chart
> Think about why you’re including this visual. What does it show that’s meaningful. There should be a point to every visual and you should tell people what to look for.
> Example: the winter months have more banana sales
> ### Link to data or source
> Don’t include this in your alt text, but it should be included somewhere in the surrounding text. People should be able to click on a link to view the source data or dig further into the visual. This provides transparency about your source and lets people explore the data.
> Example: Data from the USDA

Penn State has an [article](https://accessibility.psu.edu/images/charts/) on writing alt text descriptions for charts and tables.

> Charts, graphs and maps use visuals to convey complex images to users. But since they are images, these media provide serious accessibility issues to colorblind users and users of screen readers. See the [examples on this page](https://accessibility.psu.edu/images/charts/) for details on how to make charts more accessible.

**Comment by hardin47** [comment]
https://www.urban.org/sites/default/files/2022-12/Do%20No%20Harm%20Guide%20Centering%20Accessibility%20in%20Data%20Visualization.pdf#page=31&zoom=100,0,0

**Comment by hardin47** [comment]
done!
