### ISSUE TITLE
Question of creating a plot (Figure 7.16)

### ISSUE THREAD

**Issue by monika76five** [OpenIntroStat/ims#237]
Figure 7.16 shows a plot of an SLR with a two-level predictor and the lm fit. I am wondering how I can create a similar plot with a three-level predictor? The usual geom_smooth() does not seem to add any lines. I am considering the hsb2 dataset from OpenIntro where x = ses, y = science. Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
Maybe something like this?

``` r
library(tidyverse)
library(openintro)
#> Loading required package: airports
#> Loading required package: cherryblossom
#> Loading required package: usdata

ggplot(hsb2, aes(x = ses, y = science, group = 1)) +
  geom_jitter() +
  stat_summary(geom  = "line", fun = "mean")
```

![](https://i.imgur.com/m2Pv5FI.png)

<sup>Created on 2022-02-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
