### ISSUE TITLE
datasets & links

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#238]
I'm not exactly sure how extensive the issue is or what the fix is, but I thought I'd put the issue here for us to come back to.

contact_reason → typo
book → ims
feedback_type → other
contact_name → Mike Keim
contact_email → mkeim@putneyschool.org
reply_needed → no_but_okay

contact_message
Maybe this is an obsolete link, but I use this page in an in-class \"pick a data set\" analysis exercise: https://openintro.org/data/
and I\'ve found that many data sets are not actually in the openintro package, e.g. blizzard_salary and baby_names.
This page https://rdrr.io/cran/openintro/man/ appears to have the correct list of what\'s actually included.

Thanks for all your hard work!!! It is much appreciated. Feel free to contact me if it\'s helpful.

**Comment by mine-cetinkaya-rundel** [comment]
I believe we've aligned these now.
