### ISSUE TITLE
Chapter 7, Exercise 7

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#239]
From Paul von Hippel, [paulvonhippel@utexas.edu](mailto:paulvonhippel@utexas.edu)

The question asks \"What would be the correlation between the ages of partners if people always dated others who are 3 years younger than themselves?” But it’s impossible for everyone to date someone who is younger than themself! E.g., if you are dating someone who is 3 years younger than you, then they must be dating someone who is 3 years older than themself.

The question would be clearer though less exclusive if limited to heterosexual couples so it was clear who was younger than whom: \"What would be the correlation between the ages of husbands and wives if the wife was always (a) 2 years younger than her husband?\"

It would be nice to include same-sex couples, but I don\'t see a way to do it.

**Comment by hardin47** [comment]
or the taller person in the couple is 3 years older than the shorter person in the couple?

**Comment by hardin47** [comment]
We took out this dataset and completely changed the context (meat consumption vs carbohydrate consumption across countries).
