### ISSUE TITLE
Can't have inline code in exercise blocks

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#24]
https://github.com/OpenIntroStat/randomization-and-simulation/blob/0caad628b2b7cf3e71ac3e40f16099f8bf6c342c/02-eda.Rmd#L161

This renders as the following

<img width="802" alt="Screenshot 2020-07-06 at 21 48 48" src="https://user-images.githubusercontent.com/5965649/86640818-8b571980-bfd2-11ea-9590-386aa797e8e7.png">

This is likely due to limitations with custom blocks. Need to look into what can be done.

**Comment by hardin47** [comment]
references also don't work in any of the blocks.  i'll leave mine as is with the hopes that you come up with something magical.

**Comment by hardin47** [comment]
also, lots of images (little normal curves) in the exercises.  i'm going to put them outside the exercise for now.

**Comment by mine-cetinkaya-rundel** [comment]
@hardin47 I think I solved this now, sorry it took me a while!

Instead of using `block2` code chunks, let' use

```
::: {.guidedpractice}
Text goes here...
:::

::: {.onebox}
Text goes here...
:::

::: {.example}
Text goes here...
:::
```

etc.

Allows us to use inline code and figures as well.

<img width="2346" alt="Screenshot 2020-08-15 at 01 53 43" src="https://user-images.githubusercontent.com/5965649/90301861-48724680-de9a-11ea-8437-fc7f3dbc5fc3.png">

**Comment by hardin47** [comment]
wow, great!  you are amazing.  i have questions.

1. doesn't seem like you changed everything, right?

2. do i need to change all my boxes, or can i use either?  i.e., keep the non-changed ones as-is?

3. but i'll need to use the new format for boxes that need code or images.  

4. for guided practice, same footnote formatting, right?  so still no paragraph breaks?

**Comment by mine-cetinkaya-rundel** [comment]
1. no, i was worried about too many changes and causing you merge conflict headaches. i'd be happy to go thru and do that tomorrow morning my time. 
2. you can use either -- my ocd will probably make me want to change them all at some point, but it's not a requirement.
3. correct. so going forward i'd say use the `:::` notation.
4. correct.

**Comment by mine-cetinkaya-rundel** [comment]
@hardin47 I now removed all block2 environments.

**Comment by mine-cetinkaya-rundel** [comment]
@hardin47 this is now ok to close, right?

**Comment by hardin47** [comment]
although, tbh, as i was working through chapter 3 i found some ::: {.example} instead of ::: {.workedexample}.  i changed them to the former but didn't check the other chapters.

**Comment by mine-cetinkaya-rundel** [comment]
ah ok, let me open an issue to track that. i can do it one sweep later.
