### ISSUE TITLE
Chp 5 - statements about mean, median, mode

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#240]
From Paul Von Hippel (paulvonhippel@utexas.edu):

Chapter 5 makes a lot of the relationship between mean, median, and skewness. The relationship is not as straightforward as many people think. Please see my 2005 article "[Mean, Median,and Skew: Correcting a Textbook Rule](https://urldefense.com/v3/__https://www.tandfonline.com/doi/full/10.1080/10691898.2005.11910556__;!!OToaGQ!5oACG0ExPbLWnkJOaG0knMxcW2iiyhcjdKAqbjsdRbr2UGcO-7u_FTEaSQnSfyr7$)", especially this figure:

![image](https://user-images.githubusercontent.com/5965649/155865521-ba917615-59aa-4cff-ad69-089e1a78f7b4.png)

**Comment by hardin47** [comment]
check to make sure we use language like "tends to" instead of "is".  but we probably don't want to bring this up because it will muddy the waters.

**Comment by paulvonhippel** [comment]
The conclusion of this article makes recommendations for how to discuss the
relationship between mean, median, mode, and skewness:

Paul T. von Hippel
<http://jse.amstat.org/publications/jse>"Mean, Median, and Skew: Correcting
a Textbook Rule". Journal of Statistics Education, v13n2:
https://jse.amstat.org/v13n2/vonhippel.html

**Comment by hardin47** [comment]
I read through the chapter, and in the text of the chapter, we do not say that the mean is always greater for right skewed distributions (or anything like that).  We do say that median is robust to outliers.  Do you disagree with that sentiment?

In the exercises, we ask which is bigger: the mean or the median.  However each of the exercises is tied to a specific dataset which makes the problematic aspects moot.

Can you point to a specific phrase or idea that you find problematic?  I'm going to close this issue, but feel free to open it again with the specific phrasing that would be best to change if you find such ideas.

thanks for bringing your work to our attention, it is very interesting!
