### ISSUE TITLE
Typo - Chp 11, Sec 1, wording 

### ISSUE THREAD

**Issue by paulvonhippel** [OpenIntroStat/ims#242]
- Chapter number: 11

- Section number: 1

- Original text: The previous example is a reminder that the observed outcomes in the sample may not perfectly reflect the true relationships between variables in the underlying population.

- Suggestion for corrected text: Remove mention of sample and population. Why do you say outcomes at the start of the sentence and relationships at the end?

- Justification for suggestion: What sample? What population? This is a randomization test that involves random assignment. It does not involve sampling at random from a population.

**Comment by mine-cetinkaya-rundel** [comment]
@hardin47 Thoughts on best wording here? I wasn't sure.

**Comment by hardin47** [comment]
I changed the sentence to: "The previous example is a reminder that there will always be variability in data (making the groups differ), even if there are no underlying causes for that difference (e.g., even if there is no discrimination)."
