### ISSUE TITLE
Typo - Chp [18], Sec [4], [text missing from question 1a]

### ISSUE THREAD

**Issue by dstoebel** [OpenIntroStat/ims#244]
- Chapter number: 18

- Section number: 4

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): Question 1b

- Original text: Answer each of the following questions under the null hypothesis that being part of a support group does not affect the ability of people to quit smoking, and indicate whether the expected values are higher or lower than the observed values.

- Suggestion for corrected text: This part alludes to following questions, but they do not appear.

**Comment by mine-cetinkaya-rundel** [comment]
Duplicate of #373.
