### ISSUE TITLE
Figure 7.11. In 7 of the 8 scatterplots, the points are crowded into the top quarter of the box, making it practically impossible to see the strength of the relationship

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#252]
From Paul von Hippel:

![image](https://user-images.githubusercontent.com/5965649/164915790-2a1d311a-1719-4a54-a6bb-bc697dde8f1c.png)

**Comment by hardin47** [comment]
make a curve with the same y coordinates for the curve plot.  also overlay a lm.

**Comment by mine-cetinkaya-rundel** [comment]
Related to #253

**Comment by hardin47** [comment]
can't use scales free because then everything will look like a blob / cigar.  just fix the y coordinates of the curved plot.

**Comment by mine-cetinkaya-rundel** [comment]
Fixed when addressing #253.
