### ISSUE TITLE
Chapter 22 ANOVA: indexing means / df notation

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#256]
In the ANOVA chapter the indexing for an arbitrary mean is "i" with the number of groups as "k".  I'm not a fan.  It should be "i" and "I".  Or really, why "i"?  (As that confuses the idea of indexing observations).  Maybe "k" and "K"?  Something else?

**Comment by mine-cetinkaya-rundel** [comment]
..., where $i = 1, ..., k$ is weird, but we also say where $i = 1, ..., n$ for observations. I would say $i$ shouldn't be used for groups, but I could see $j = 1, ..., k$, only because we do use $i = 1, ..., n$. 

I'd be ok with k and K but worried about consistency with other resources.

**Comment by hardin47** [comment]
ok, i'll change to $j = 1, \ldots, k$  (after confirming that we don't index with $j$ elsewhere)

**Comment by hardin47** [comment]
switched to $j = 1, \ldots, k$ in ANOVA section.
