### ISSUE TITLE
Use openintro logo for favicon

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#257]
I forget what this is called (favicon?), but we should have an openintro icon in the web tab instead of the default globe:

![image](https://user-images.githubusercontent.com/7210585/171466714-28c38268-0d81-4d4f-9fa4-ca0849867214.png)

**Comment by mine-cetinkaya-rundel** [comment]
This is done now, https://github.com/OpenIntroStat/ims/blob/6f647c497d2a0cb9b7beaa925fabe4a2cb19b75d/_quarto.yml#L14.
