### ISSUE TITLE
Typo - chapter 17 in printed book, wrong page header

### ISSUE THREAD

**Issue by rmorsomme** [OpenIntroStat/ims#262]
- Chapter number: 17

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): page header in printed book

- Original text: Chapter 17: Bootstrap CI for the difference in proportion

- Suggestion for corrected text: Inference for comparing two proportions

- Justification for suggestion: page header should correspond to chapter title

**Comment by mine-cetinkaya-rundel** [comment]
This is the section title, so it's ok as is, thank you!
