### ISSUE TITLE
Typo - Chp 17, Sec 5, exercise 17.13 has wrong solution

### ISSUE THREAD

**Issue by rmorsomme** [OpenIntroStat/ims#263]
- Chapter number: 17

- Section number: 5

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): exercise 17.13

- Solution 17.13 in the appendix does not correspond to exercise 17.13. However, solution 17.15 corresponds to exercise 17.13.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
