### ISSUE TITLE
Section 20.4 (CI) should come before Section 20.3 (HT)

### ISSUE THREAD

**Issue by rmorsomme** [OpenIntroStat/ims#265]
The order of Sections 20.4 (CI) and 20.3 (HT) should be switched.
Section 20.4 (CI) provides the details of the SE which are necessary to do the Guided Practice in Section 20.3.3.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you! The SE is given in https://openintro-ims2.netlify.app/20-inference-two-means#observed-statistic-vs.-null-statistics-1 so I think we're good here.
