### ISSUE TITLE
Typo - Chp [20], Sec [6], Exercises 20.14 and 20.19 are identical

### ISSUE THREAD

**Issue by rmorsomme** [OpenIntroStat/ims#266]
- Chapter number: 20

- Section number: 6

- Exercises 20.14 and 20.19 are identical

**Comment by mine-cetinkaya-rundel** [comment]
This is the `gaming_distracted_eating_intake` question, we should indeed remove one, and will need to add a question in its place.

**Comment by hardin47** [comment]
i took out `gaming_distracted_eating_intake` and replaced it with `mindful_nurse`.
