### ISSUE TITLE
Show that paired t-test is more powerful than two-sample t-test

### ISSUE THREAD

**Issue by rmorsomme** [OpenIntroStat/ims#269]
It would be nice to add a section to chapter 21 (paired t-test) to show that a paired t-test is more powerful than a two-sample t-test.
This can easily be done with the tire data from Section 21.1 and 22.2. Simply add a random effect for the cars with the following `R` code

bias <- runif(25, -0.01, 0.01) # random effect
brandA <- rnorm(25, bias + 0.310, 0.003)
brandB <- rnorm(25, bias + 0.308, 0.003)

instead of 

brandA <- rnorm(25, 0.310, 0.003)
brandB <- rnorm(25, 0.308, 0.003)

This random effect gives a paired t-test with a p-value of 0.01 and a narrow CI, and a two-sample t-test with a p-value of 0.22 and a much larger CI.

**Comment by hardin47** [comment]
maybe this should go in chp 21 instead of 14 (or both?) because pairing hasn't yet been introduced in chp 14.

**Comment by hardin47** [comment]
I added a note on power to chapters 14, 20, and 21.  thanks for the suggestion!
