### ISSUE TITLE
names of things

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#27]
Chapter 5:

Laying the groundwork for statistical inference?

Too long?

 What about:

 
* A First Encounter with Statistical Inference

* Beginnings of Statistical Inference

* Introduction of Statistical Inference

--------------------

How about just "The Groundwork for Statistical Inference"

**Comment by hardin47** [comment]
Book title:

Statistics with Modern Methods
Intro Statistics with Modern Methods
Intro Modern Statistics

(I can't remember what you wrote down today.)

**Comment by mine-cetinkaya-rundel** [comment]
- Introduction to Statistics with Computational Approaches/Methods
- Introduction to Statistics with Simulation-based Approaches/Methods

**Comment by mine-cetinkaya-rundel** [comment]
Introduction to Modern Statistics is what we landed on

**Comment by beanumber** [comment]
So many "modern" books!
