### ISSUE TITLE
Typo - Chp [25], Sec [5], wrong list symbol

### ISSUE THREAD

**Issue by rmorsomme** [OpenIntroStat/ims#276]
- Chapter number: 25

- Section number: 5

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): Exercise 25.2

- Original text: Exercise 25.1.2

- Suggestion for corrected text: Exercise 25.1.b

- Justification for suggestion: list of sub-questions should be **a, b**; instead of **a, 2**

**Comment by mine-cetinkaya-rundel** [comment]
Couldn't find the location yet, leaving it for v2 edits

**Comment by mine-cetinkaya-rundel** [comment]
I think this is fixed.
