### ISSUE TITLE
Accessibility/inclusivity ideas

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#28]
See https://twitter.com/WeAreRLadies/status/1286823386115534849?s=20

**Comment by mine-cetinkaya-rundel** [comment]
Also, we should add `fig.alt` to figures, which will be an undertaking but a worthwhile effort. Useful to keep in mind for new figures we're generating @hardin47. The sweep for updating older figures can happen during edits or after we focus efforts on getting print edition out.

**Comment by hardin47** [comment]
meant to ask you about this.  can you be a little more specific?  what should i make sure to do?

**Comment by mine-cetinkaya-rundel** [comment]
Ah, yeah! In R chunks where the output is a figure, you can now add a new knitr chunk option (`fig.alt`) that places alt text. Since we write captions already, the most important information might already be captured there. But anything that would make the figure accessible for visual impairments that is not captured in the caption should go in `fig.alt`, e.g. `fig.alt = "Alt text goes here"`).

**Comment by hardin47** [comment]
so maybe something like "the points have been colored to represent each group and the graph shows most of the red points (from group A) are on the left and most of the blue points (from group B) are on the right."

**Comment by mine-cetinkaya-rundel** [comment]
Yup, I found [this resource](https://accessibility.huit.harvard.edu/describe-content-images) helpful.
