### ISSUE TITLE
Typo - Chp [Appendix], Sec [A.21], wrong answer

### ISSUE THREAD

**Issue by rmorsomme** [OpenIntroStat/ims#282]
- Chapter number: Appendix

- Section number: A.21

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): Answer A.21.9.d

- Original text: No and yes

- Suggestion for corrected text: Yes (or the answer is No if the order in the randomized sample needs to match that of the observed sample)

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
