### ISSUE TITLE
Potential paired t-test example

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#286]
https://twitter.com/Notawful/status/1554462497477894149

**Comment by hardin47** [comment]
here is another one (hilarious!):  http://notawfulandboring.blogspot.com/2019/08/seagull-thievery-deterrent-research.html

**Comment by hardin47** [comment]
both are great examples for paired t-tests.

**Comment by hardin47** [comment]
https://notawfulandboring.blogspot.com/2022/08/another-recent-publication-with-lots-of.html

**Comment by hardin47** [comment]
closed and tracked at #407
