### ISSUE TITLE
Typo - Chp 16, Sec 1.3, simulation seems wrong

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#291]
- Chapter number: 16

- Section number: 1.3

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): Near Figure 16.1

Simulated frequency of 420 has to be for complications <= 2 instead <= 3.
Expected frequency for <= 3 using the binomial distribution is 1210, and for <= 2 450.
So the p-value for <= 0.048 has to be around 0.121.
The bar in Figure 16.1 over 5 has to be blue, too.
Subsequent conclusions are also wrong.

submitted by: [karsten_bonk@yahoo.de](mailto:karsten_bonk@yahoo.de)

**Comment by mine-cetinkaya-rundel** [comment]
@hardin47 I assigned this back to you because I'm not sure I follow the comment. I'm probably missing something but thought you might have more context.

**Comment by hardin47** [comment]
We need to change the simulation to be p_sim <= 0.0484 (round up instead of round down) to catch the actual observed value.  I think it will make the p-value 0.121-ish, so not statistically discernible (narrative will also need to change).

**Comment by hardin47** [comment]
I fixed the question, but I think maybe we are replacing the entire example of the medical consultant.  See issue #409 .
