### ISSUE TITLE
Typo - Chp [18], Sec [1.1], [typo in formulas for expected counts]

### ISSUE THREAD

**Issue by s-k-pike** [OpenIntroStat/ims#295]
- Chapter number: 18

- Section number: 1.1

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): ___

- Original text: 
Looking back to how 0.2785 was computed -- as the fraction of sellers who disclosed the freezing issue $(158/219)$ -- these three expected counts could have been computed as

$$
\begin{aligned}
\left(\frac{\text{row 1 total}}{\text{table total}}\right)
    \text{(column 1 total)} &= 20.33 \\
\left(\frac{\text{row 1 total}}{\text{table total}}\right)
    \text{(column 2 total)} &= 20.33 \\
\left(\frac{\text{row 1 total}}{\text{table total}}\right)
    \text{(column 3 total)} &= 20.33
\end{aligned} 
$$

- Suggestion for corrected text: 
Looking back to how 0.2785 was computed -- as the fraction of sellers who disclosed the freezing issue $(61/219)$ -- these three expected counts could have been computed as

$$
\begin{aligned}
\left(\frac{\text{column 1 total}}{\text{table total}}\right)
    \text{(row 1 total)} &= 20.33 \\
\left(\frac{\text{column 1 total}}{\text{table total}}\right)
    \text{(row 2 total)} &= 20.33 \\
\left(\frac{\text{column 1 total}}{\text{table total}}\right)
    \text{(row 3 total)} &= 20.33
\end{aligned} 
$$

- Justification for suggestion: 158 is the number of sellers who *hide* the freezing issue
and compared with the formulas given above with the 0.2785 instead of the fractions, it seems like "column" and "row" have been switched in these formulas, hence swapping them here so they agree with formulas above

**Comment by mine-cetinkaya-rundel** [comment]
Thanks!
