### ISSUE TITLE
links to things that are broken

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#30]
In chapter 7, ANOVA

www.openintro.org/d?file=stat\_extra\_anova\_calculations

**Comment by mine-cetinkaya-rundel** [comment]
@DavidDiez Might you know where this moved?

**Comment by hardin47** [comment]
Ahhh!  Sorry, just realized that it was a LaTeX to Markdown issue!!!  The URL is just fine here:  www.openintro.org/d?file=stat_extra_anova_calculations
