### ISSUE TITLE
Add updates to 2e in Preface

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#305]
Keep a running list of major changes

**Comment by hardin47** [comment]
I did write something a few weeks ago.  The file is [changes_v2.qmd](https://github.com/OpenIntroStat/ims/blob/main/changes_v2.qmd).  I don't know where the file "belongs" in the book.

One thing is that I lied about a new dataset.  The new dataset *does* exist in the [openintro dataset package repo](https://github.com/OpenIntroStat/openintro/blob/main/data/pm25_2022_durham.rda), but it doesn't exist on the openintro webpage (which I point to in the changes doc): [http://openintrostat.github.io/openintro/reference/pm25_2022_durham.html](http://openintrostat.github.io/openintro/reference/pm25_2022_durham.html)

**Comment by mine-cetinkaya-rundel** [comment]
I'm good with adding this as a subsection to the existing preface or adding a specific preface a la https://r4ds.hadley.nz/preface-2e. Do you have a preference? Feel free to choose one and go with it.

Re: dataset -- I have it on the to do list to update the openintro package along with this so don't worry about the "lie", it'll be a reality by the time we call 2e done.

**Comment by hardin47** [comment]
My instinct is to have two separate "pages".  I think we sort of need the original preface part because it walks the reader through all the pieces of the book.  

And then we can have a separate page for the changes.  I'll implement and you can tell me what you think?

**Comment by mine-cetinkaya-rundel** [comment]
Sounds good

**Comment by hardin47** [comment]
i added in the file.  feel free to edit in whatever way makes sense to you.
