### ISSUE TITLE
Found example confusing

### ISSUE THREAD

**Issue by ghmorrison** [OpenIntroStat/ims#323]
Example:
Yousef’s height is at the 40th percentile. How tall are they?

https://github.com/OpenIntroStat/ims/blob/main/13-foundations-mathematical.qmd

Line 710: qnorm(0.4, mean = 0, sd = 1)

I could not figure out why the mean was 0 or the standard deviation was 1

If I am doing it right. "qnorm(0.4, mean = 70, sd  = 3.3) " makes more sense

**Comment by mine-cetinkaya-rundel** [comment]
The former will give you the Z score, and then you can work out the height. The latter (your solution) will give you the height directly. Either approach is valid. Since we wanted to discuss Z-scores here as well, I think it makes sense to leave it as is, what do you think @hardin47?

**Comment by hardin47** [comment]
what if I expand it to include both ways (and give some narrative about why).  does that make the question better or does it become too long?

**Comment by mine-cetinkaya-rundel** [comment]
I think that would work @hardin47!

**Comment by ghmorrison** [comment]
I think @hardin47's idea of showing both ways would be worth any additional text. Thanks.

**Comment by ghmorrison** [comment]
To me if all you want is the z value, it made more sense not to enter the  default mean and standard deviation. 
qnorm(0.4) # uses default mean of 0 and Standard deviation of 1
Explaining how to use R to get the final answer adds value because if you stop at the z value I would have thought I had to enter the equation separately.

**Comment by hardin47** [comment]
hopefully fixed here: https://github.com/OpenIntroStat/ims/commit/b5aaf1a490824d7484fc3627b47f68f4dcb628ab

re-open this issue if anyone sees additional problems.
