### ISSUE TITLE
Typo - Chp [4], Sec [1], [code referencing other chapters didn't work]

### ISSUE THREAD

**Issue by alice-gaeun** [OpenIntroStat/ims#327]
- Chapter number: 4

- Section number: 1 and many others

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): has @ before it

- Original text: "The loan50 dataset from Chapter @ref(data-hello)..." or another @ and message that doesn't reference something correctly.

<img width="580" alt="Screenshot 2023-09-10 at 12 01 12 PM" src="https://github.com/OpenIntroStat/ims/assets/144613505/8172c0ca-3c80-42b6-ad5d-210a9a96d954">

<img width="576" alt="Screenshot 2023-09-10 at 12 01 59 PM" src="https://github.com/OpenIntroStat/ims/assets/144613505/62080652-95e1-40b7-994c-d64ad738dfc7">

- Suggestion for corrected text: \@ref(data-hello)

- Justification for suggestion: I actually searched this up, and the first thing I saw was that you should reference sections by using \@ref().

**Comment by mine-cetinkaya-rundel** [comment]
Thank you! Addressed in b06292e.
