### ISSUE TITLE
Typo - Chp [8], Sec [1], [linear regression models not formatted legibly, in teletype font but not complete]

### ISSUE THREAD

**Issue by sharonxd13** [OpenIntroStat/ims#331]
- Chapter number: 8

- Section number: 1

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): all text for regression models or parts of the model

- Original text: \begin{aligned} \widehat{\texttt{interest_rate}} &= 11.10 \\ &+ 1.42 \times \texttt{verified_income}_{\texttt{Source Verified}} \\ &+ 3.25 \times \texttt{verified_income}_{\texttt{Verified}} \end{aligned}

- Suggestion for corrected text: reformatted to show the text in LaTeX, visually legibly, without the source formatting

- Justification for suggestion: very difficult to read and does not fit in provided text space

**Comment by mine-cetinkaya-rundel** [comment]
I think this is all corrected now, thank you!
