### ISSUE TITLE
equations in text

### ISSUE THREAD

**Issue by aminamaatoug** [OpenIntroStat/ims#333]
almost all the equations are showing up like this: red text highlighted in yellow as seen in the picture.

**Comment by mine-cetinkaya-rundel** [comment]
Which chapter are you seeing this in, can you link to it?

**Comment by aminamaatoug** [comment]
In chapters 7 (https://openintro-ims2.netlify.app/07-model-slr). It appears like this: \widehat{\texttt{aid}} = \beta_0 + \beta_{1}\times \texttt{family_income}
