### ISSUE TITLE
Typo - Chp [8], Sec [4.1], [missing parentheses]

### ISSUE THREAD

**Issue by sharonxd13** [OpenIntroStat/ims#335]
- Chapter number: 8

- Section number: 4.1

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): 8.4.1 second paragraph

- Original text: Backward elimination starts with the full model (the model that includes all potential predictor variables. Variables are eliminated one-at-a-time from the model until we cannot improve the model any further.

- Suggestion for corrected text: Backward elimination starts with the full model (the model that includes all potential predictor variables). Variables are eliminated one-at-a-time from the model until we cannot improve the model any further.

- Justification for suggestion: closing parentheses for clarification

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
