### ISSUE TITLE
Inconsistency regarding the classification of the "year" variable

### ISSUE THREAD

**Issue by LingjiaZhu** [OpenIntroStat/ims#338]
I observed an inconsistency regarding the classification of the "year" variable. In the book, "year" is classified as a discrete variable, which aligns with common statistical understanding. However, the feedback from the lab indicates it's continuous. To prevent further confusion among students, I suggest aligning the classification across both the book and the lab materials.

**Comment by mine-cetinkaya-rundel** [comment]
This appears to be a course related question. I'll close here, please ask on the course Slack!
