### ISSUE TITLE
Chapter 8 Exercise 9d. is wrong

### ISSUE THREAD

**Issue by gargi2358** [OpenIntroStat/ims#339]

**Comment by mine-cetinkaya-rundel** [comment]
Can you provide more context please?

**Comment by gargi2358** [comment]
7.13 is not the residual. Rather, it is the predicted value. The observed value is 6.96. 
residual = observed value - predicted value
residual = 6.96 - 7.13
residual = -0.17

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
