### ISSUE TITLE
Typo - Chp [___], Sec [___], [__wrong name in Lab 5 Ex6__]

### ISSUE THREAD

**Issue by LingjiaZhu** [OpenIntroStat/ims#347]
- Chapter number: Lab 5

- Section number: Ex 6

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): After code

- Original text: inspect the object **null_dist_transplant**

- Suggestion for corrected text:  inspect the object **null_dist_outcome**

- Justification for suggestion: the original name does not exist

**Comment by mine-cetinkaya-rundel** [comment]
Thanks, this is in the course materials, not the book, but I fixed there.
