### ISSUE TITLE
Typo - Chp [11], Sec [11.1.1], ["suggest" should be "suggests]

### ISSUE THREAD

**Issue by jqzjqz0707** [OpenIntroStat/ims#351]
- Chapter number: 11

- Section number: 11.1.1

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): Under Figure 11.1

- Original text: The large difference in promotion rates (58.3% for female personnel versus 87.5% for male personnel) suggest there might be discrimination against women in promotion decisions.

- Suggestion for corrected text: The large difference in promotion rates (58.3% for female personnel versus 87.5% for male personnel) **suggests** there might be discrimination against women in promotion decisions.

- Justification for suggestion: wrong grammar

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
