### ISSUE TITLE
Typo - Chp [11], Sec [11.4.1], ["existance" should be "existence"]

### ISSUE THREAD

**Issue by jqzjqz0707** [OpenIntroStat/ims#353]
- Chapter number: 11

- Section number: 11.4.1

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): near figure 11.8

- Original text: The alternative hypothesis usually represents a new view or the **existance** of a relationship between the variables.

- Suggestion for corrected text: The alternative hypothesis usually represents a new view or the **existence** of a relationship between the variables.

- Justification for suggestion: "existance" should be "existence"

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
