### ISSUE TITLE
Typo - Chp [13], Sec [13.1], [Mislabeled Chapter Number and Missing Link]

### ISSUE THREAD

**Issue by BowenKim** [OpenIntroStat/ims#355]
- Chapter number: 13

- Section number: 13.1

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): -

- Original text: For example, some of the scenarios encountered in (Chapter sec?-model-mlr) where we introduced regression models with multiple predictors would require complex simulations in order to make inferential conclusions.

- Suggestion for corrected text: For example, some of the scenarios encountered in (Chapter 8) where we introduced regression models with multiple predictors would require complex simulations in order to make inferential conclusions.

- Justification for suggestion: My suggestion provides the correct chapter number for regression models with multiple predictors. I believe the previous text was compromised by a malfunctioning link because the link also did not work.

**Comment by mine-cetinkaya-rundel** [comment]
Fixed, thank you!
