### ISSUE TITLE
Typo - Chp [13], Sec [13.2.1], [Typo Regarding Singular vs. Plural]

### ISSUE THREAD

**Issue by BowenKim** [OpenIntroStat/ims#356]
- Chapter number: 13

- Section number: 13.2.1

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): -

- Original text: A normal distributions with mean 19 and standard deviation 4 is shown on the right.

- Suggestion for corrected text: A normal distribution with mean 19 and standard deviation 4 is shown on the right.

- Justification for suggestion: My suggestion uses correct grammatical language in which I removed an "s" after distribution because the text conveys that a single distribution is being shown on the right, not multiple.

**Comment by BowenKim** [comment]
Actually, though my suggestion still holds, I should suggest that the new text should say "Normal distributions with mean 19 and standard deviation 4 is shown on the right" because the text refers to multiple distributions. However, the "a" must be removed.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
