### ISSUE TITLE
Typo - Chp [16], Sec [16.1], [Unclear Chapter References]

### ISSUE THREAD

**Issue by BowenKim** [OpenIntroStat/ims#358]
- Chapter number: 16

- Section number: 16.1

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.):-

- Original text: The bootstrap simulation concept when H0 is true is similar to the ideas used in the case studies presented in Chapter @ref(foundations-bootstrapping) where we bootstrapped without an assumption about H0.

- Suggestion for corrected text: The bootstrap simulation concept when H0 is true is similar to the ideas used in the case studies presented in Chapter 12 where we bootstrapped without an assumption about H0.

- Justification for suggestion: My suggestion includes the correct chapter reference for the above text. A quick note: I don't think the Chapter References/Link work for this entire chapter. There are multiple instances of the above in the introduction and throughout the text. If you would like more specific instances for your convenience, I would be happy to provide them!

**Comment by mine-cetinkaya-rundel** [comment]
Closed with eafdb81, thank you!
