### ISSUE TITLE
Typo - Chp [exam review], Sec [exam 2], [95% should be 90%]

### ISSUE THREAD

**Issue by jqzjqz0707** [OpenIntroStat/ims#368]
- Chapter number: exam review

- Section number: exam 2

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): the answer for Question 10 

- Original text: The correct interpretation is “We are **95%** confident that 40% to 80% of statistics majors work at least 5 hours per week.

- Suggestion for corrected text: The correct interpretation is “We are **90%** confident that 40% to 80% of statistics majors work at least 5 hours per week.

- Justification for suggestion: 95% should be 90%, because Q9 asks the 90% confidence interval.

**Comment by mine-cetinkaya-rundel** [comment]
This is course material related, not textbook.
