### ISSUE TITLE
ch 17 answer key for #13 doesn't match up 

### ISSUE THREAD

**Issue by isabellarose3456** [OpenIntroStat/ims#369]
- Chapter number: 17

- Section number: 13

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): ___

- Original text: question 13 is about yawning contagious

- Suggestion for corrected text: but answer key for question 13 refers to soda preference 

- Justification for suggestion: the key doesn't match

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
