### ISSUE TITLE
ch 18 missing question part #1 b

### ISSUE THREAD

**Issue by isabellarose3456** [OpenIntroStat/ims#373]
- Chapter number: 18

- Section number: 1

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): Quitters ___

- Original text: _Answer each of the following questions under the null hypothesis 

- Suggestion for corrected text: There are no following questions, the key mentions part bi and bii but the i and ii parts are not shown in the question 

- Justification for suggestion: ___

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
