### ISSUE TITLE
Typo - Chp [13], Sec [13.3.3], [_interpretation of margin of error__]

### ISSUE THREAD

**Issue by 2762553** [OpenIntroStat/ims#374]
- Chapter number: 13

- Section number: 13.3.3

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): the first paragraph

- Original text: To describe where most (i.e., 95%) observations lie, we say that the margin of error is approximately 2*SE.  That is, 95% of the observations are within one margin of error of the mean.

- Suggestion for corrected text:  To describe where most (i.e., 95%) observations lie, we say that the margin of error is approximately 2*SE.  That is, 95% of the observations are within two margins of error of the mean.

- Justification for suggestion: 2*SE corresponds with two margins of error of the mean and 95% of observations approximately.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
