### ISSUE TITLE
Ch 18 Red Flag Box Titled "Computing expected counts in a two-way table."

### ISSUE THREAD

**Issue by ajp95** [OpenIntroStat/ims#393]
The box titled "Computing expected counts in a two-way table." makes reference to the ith row and jth column, but there is never elaboration on which row and column these are referring to. It would be useful to have more information, maybe in relation to the iPod example, of which column and which row are being referened.

**Comment by mine-cetinkaya-rundel** [comment]
It's not referring to a specific row and column, the notation means any row and any column.
