### ISSUE TITLE
Typo - Chp [chapter 14], Sec [14.1], ["lead" should be "leads"]

### ISSUE THREAD

**Issue by jqzjqz0707** [OpenIntroStat/ims#396]
- Chapter number: chapter 14

- Section number: 14.1

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): under the blue box

- Original text: However, what distinguishes statistical hypothesis tests from a court system is that our framework allows us to quantify and control how often the data **lead** us to the incorrect conclusion.

- Suggestion for corrected text: However, what distinguishes statistical hypothesis tests from a court system is that our framework allows us to quantify and control how often the data **leads** us to the incorrect conclusion.

- Justification for suggestion: "lead" should be "leads"

**Comment by mine-cetinkaya-rundel** [comment]
Data can be plural, so no correction needed here.
