### ISSUE TITLE
Typo - Exam 2 Review Answer Key, [Question 10: incorrect confidence interval upper bound] 

### ISSUE THREAD

**Issue by ajp95** [OpenIntroStat/ims#397]
- Location: Answer Key for Exam 2 Review, question 10. 

- Original text: "We are 95% confident that 40% to 90% of statistics majors work at least 5 hours per week."

- Suggestion for corrected text: “We are 95% confident that 40% to 80% of statistics majors work at least 5 hours per week."

- Justification for suggestion: As per the answer to question 9, the 95% CI ranges from 40% to 80%. Sorry if I'm misunderstanding the confidence interval, but I believe this interval should also apply to question 10

**Comment by mine-cetinkaya-rundel** [comment]
This is in the course materials, not textbook, so recorded at https://github.com/sta101-f23/sta101-f23.github.io/issues/3 instead.
