### ISSUE TITLE
Typo - AE-14 Answer Key, Exercise 1 Typo

### ISSUE THREAD

**Issue by ajp95** [OpenIntroStat/ims#398]
- AE-14 Answer Key, Exercise 1

- Original text: 
H0: Issue of choice and party affiliation are independent.
HA: Issue of choice and party affiliation are independent.

- Suggestion for corrected text: 
H0: Issue of choice and party affiliation are independent.
HA: Issue of choice and party affiliation are not independent.
OR
H0: Issue of choice and party affiliation are independent.
HA: Issue of choice and party affiliation are dependent.

- Justification for suggestion: H0 and HA cannot be the same. H0 means nothing is going on and the two variables are independent. HA means there is something going on and the two variables are not independent.

**Comment by mine-cetinkaya-rundel** [comment]
This is in the course materials, not textbook, so recorded at https://github.com/sta101-f23/sta101-f23.github.io/issues/2 instead.
