### ISSUE TITLE
Markdown Issue w. Ch. 9 Exercise Solutions

### ISSUE THREAD

**Issue by senecarussell** [OpenIntroStat/ims#401]
Hello! In the chapter 9 exercise solutions, the Markdown equation for the logistic model appears as red text with a yellow background and is difficult to read. I have included a photo below. Thank you!
<img width="1351" alt="Screen Shot 2023-11-16 at 2 10 22 AM" src="https://github.com/OpenIntroStat/ims/assets/146801999/e534dca6-876d-41c4-9d71-e1d9e69d614e">

**Comment by hardin47** [comment]
I think this is fixed (in both A and SA), but I won't know for sure until I can see the compiled version.

**Comment by hardin47** [comment]
fixed
