### ISSUE TITLE
Types of Simulations for Confidence Intervals and Hypothesis Testing

### ISSUE THREAD

**Issue by sierrasewchand** [OpenIntroStat/ims#402]
Hello! I have a few suggestions when teaching about the different type of simulations for hypothesis testing and confidence intervals. I had a difficult time understanding the differences between each simulation such as what the difference was between bootstrapping and permuting and how they differed based on a null hypothesis or when the data was placed into "bins" before random selection.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the feedback!
