### ISSUE TITLE
Typo - Chp [7], Sec [16], Exercise which is higher

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#405]
bullet points are messed up

<img width="857" alt="Screenshot 2023-11-17 at 2 47 33 PM" src="https://github.com/OpenIntroStat/ims/assets/5965649/21192d5d-d9f9-493a-81da-2bf6c0c3ea7f">

**Comment by hardin47** [comment]
fixed.  the problem wasn't bullet points, it was the formatting of $b_1$.  the wording of the problem is slightly wonky, but i didn't change it.
