### ISSUE TITLE
Typo - Chp [20], Sec [Exercise 6], [calculating "true population difference in price per carat" for lizards?]

### ISSUE THREAD

**Issue by danielishih** [OpenIntroStat/ims#427]
- Chapter number: 20

- Section number: Exercise 6

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): prompt

- Original text: "true population difference in price per carat for"

- Suggestion for corrected text: "true population difference in average speed of"

- Justification for suggestion: We are assessing the running speeds of the lizards not the price per carat of a lizard. The price per carat phrasing is from the question before.

**Comment by hardin47** [comment]
thanks for the good catch!  i was working in the exercises this morning, so i have made the change.
