### ISSUE TITLE
Typo - Chp [26.4], [Chapter Review Summary], [early v earlier]

### ISSUE THREAD

**Issue by angel-808** [OpenIntroStat/ims#433]
- Chapter number: 26.4

- Section number: 26.4.1 Summary

- Other location identifier, if any (e.g., figure number, table number, footnote number, etc.): Second sentence of the chapter review summary. 

- Original text: "Early we presented graphical techniques which communicated relationships across multiple variables."

- Suggestion for corrected text: "Earlier in the chapter, we introduced graphical techniques that effectively illustrated relationships among multiple variables."

- Justification for suggestion: Enhances clarity and readability by providing more specific and structured information about the introduction of graphical techniques while using the right tense of the word "early".

**Comment by hardin47** [comment]
just changed to "earlier" not "earlier int he chapter"

**Comment by hardin47** [comment]
reopened in case you need to assign extra credit

**Comment by hardin47** [comment]
also, i didn't fix this after all because i'm confused about PRs, so I'm going to hold off until my files are in sync with the rest of the repo.
