### ISSUE TITLE
solutions need to happen

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#447]
all SA and A files need to be compiled and copied over from the exercise repo

**Comment by hardin47** [comment]
the SA formatting is still a little off.  For example, see:

![image](https://github.com/OpenIntroStat/ims/assets/7210585/ce73eb37-3956-4469-9329-a1d2fb28c355)


and

![image](https://github.com/OpenIntroStat/ims/assets/7210585/d58e0bca-b1a1-4250-ae7d-90f0e0c1d637)

**Comment by mine-cetinkaya-rundel** [comment]
We're in a "as good as it gets" place with the long eqns and they look ok in PDF so I'll stop trying to fix here. The other issue is resolved.
