### ISSUE TITLE
chapter 8, table 8.2

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#448]
i don't know how to fix the back ticks and asterisks for variable names an italices

![image](https://github.com/OpenIntroStat/ims/assets/7210585/9ef2d371-6ac1-4c91-af33-a45b712c035a)

**Comment by gungorMetehan** [comment]
The codes are working in default settings.
![kableExtra](https://github.com/OpenIntroStat/ims/assets/102655648/caef4078-6100-4dd9-81d3-a5fa9f4a026e)

Try to add `format = "markdown"` argument to the `kbl()` function. It may work.

**Comment by mine-cetinkaya-rundel** [comment]
This must have been a temporary issue, it looks ok for me locally.
