### ISSUE TITLE
chp 24 order of exercises

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#450]
I changed the order of exercises so that a student could work through all the parts with a single dataset for *evens*  or for *odds*.  

Here is the original ordering:

![image](https://github.com/OpenIntroStat/ims/assets/7210585/6247f26a-e9ed-42b0-8e41-205774adbda2)

Here is the ordering I changed it to:

![image](https://github.com/OpenIntroStat/ims/assets/7210585/52a72c6b-b7a1-443c-af03-c6f8f402b2c2)

**Comment by hardin47** [comment]
chapter 21 is all over the place.  should i reorder?

![image](https://github.com/OpenIntroStat/ims/assets/7210585/8a55cc92-ddd6-47d1-8084-7c935a745021)

**Comment by mine-cetinkaya-rundel** [comment]
sure i think esp for the later chapters this is totally fine and now is a good time to clean up

**Comment by hardin47** [comment]
fixed
