### ISSUE TITLE
formatting consistency

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#453]
I'm not sure where to put this, but I wanted to remember for V3

dataset (one word)
data frame (two words)
Type I error

**Comment by hardin47** [comment]
box plot (two words)

**Comment by mine-cetinkaya-rundel** [comment]
These are addressed in v2

**Comment by hardin47** [comment]
right, right, all done for v2.

that said, i tagged it as v3 so that i would remember when we came back to v3.  but maybe an "issue" isn't the right place to "store" this information (which i will most certainly forget).

**Comment by mine-cetinkaya-rundel** [comment]
@hardin47 I see. I'd suggest we add a section to README like "style" or "conventions" and note them there?

**Comment by hardin47** [comment]
done
