### ISSUE TITLE
figure link is wonky in first part narrative

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#454]
The code connecting to the figure looks right, but the link that shows up is wonky.  I'm not sure how to fix it.

![image](https://github.com/OpenIntroStat/ims/assets/7210585/1d6b38e9-4365-47e4-ae34-d4355d8ddb6e)

**Comment by mine-cetinkaya-rundel** [comment]
The figure link should be fixed now, the chapter links are still wonky.
