### ISSUE TITLE
fix references

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#458]
I've been fixing the references as I come across problematic ones.  However, they are all formatted pretty differently in the .bib file.  I think that one thing which would help make them seem more consistent is if we used a style file that took only first initial (instead of first name).  do you know an easy way to do that?

![image](https://github.com/OpenIntroStat/ims/assets/7210585/153648d7-145a-45d6-bd39-c30d6a149d98)

**Comment by mine-cetinkaya-rundel** [comment]
Applied that fix to all entries
