### ISSUE TITLE
[Table 13.2] - Identical cells

### ISSUE THREAD

**Issue by gungorMetehan** [OpenIntroStat/ims#461]
![table 13 2](https://github.com/OpenIntroStat/ims/assets/102655648/1de9e981-fce0-4b9b-af60-8c17a74e0e6a)
As you see, (2, 2) and (3,2) are exactly the same.

**Comment by hardin47** [comment]
I think they are supposed to be the same.

**Comment by mine-cetinkaya-rundel** [comment]
Clarified a bit more, thanks!
