### ISSUE TITLE
edits through the end!!

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#472]
A footnote to fix

![image](https://github.com/OpenIntroStat/ims/assets/7210585/bd927cb3-d8eb-4e3e-ade7-6ef103665b18)

**Comment by hardin47** [comment]
I don't think the table caption for 23.1 should be "hello" ?!?!  How about "Summary of one and two proportion inference."  ?

Or if we want it to match 23.2 then it should be something like "Similarities of z-methods across one sample and two independent samples
analysis of a binary response variable. p represents the population proportion, p-hat represents the sample proportion, p_0 represents the null hypothesized proportion, p-hat_pool represents the pooled proportion, and 𝑛 represents the sample size. The subscripts of 1 and 2 indicate
that the values are measured separately on sample 1 and sample 2."

![image](https://github.com/OpenIntroStat/ims/assets/7210585/00c37813-a8df-4142-8b96-08e06e388893)

**Comment by hardin47** [comment]
would be great to get page 475 onto page 474

![image](https://github.com/OpenIntroStat/ims/assets/7210585/eb8522e6-e6b2-4f34-bffc-cda1b439d5ab)

**Comment by mine-cetinkaya-rundel** [comment]
All done!
