### ISSUE TITLE
Question idea confounding

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#49]
The speed and height question from OS4 (8.9, page 314) is great for thinking about a confounding variable but I don't like the binary gender and the suggestion that one gender might drive faster than the other. It would be great to generate a pair of questions like this for Section 3.1 of IMS. @hardin47 if you have any ideas, let me know and I'm happy to write the question. I'll keep thinking too.

**Comment by hardin47** [comment]
1. SAT scores: https://beanumber.github.io/mdsr2e/ch-foundations.html#sec:confound

2. There's a good example in Chapter 6 of Moore's BPS - on-time airline flights between Alaska Airlines and America West - to Phoenix and Seattle.  Weather (and the number of flights) are the lurking variables that explain the difference.

3. I got this here:  https://www.causeweb.org/cause/resources/fun/quotes/nightingale-confounding  could be good?  

> In comparing the deaths of one hospital with those of another, any statistics are justly considered absolutely valueless which do not give the ages, the sexes and the diseases of all the cases.  - Florence Nightingale (1820 - 1910)

4. eating organic, lifespan, confounded by wealth in general

**Comment by hardin47** [comment]
i think we don't have that question any longer.  so are we looking to add some additional confounding questions?  i added a V2 tag.

**Comment by hardin47** [comment]
I added a handful of questions:  confounding in chapter 2 (`meat_cat_confound` and `nightingale`); simpson's paradox in chapter 2 (`flights_cat_sp` and `congress`); sp in chapter 8 (`flights_reg_sp`); and confounding in chapter 8 (`meat_reg_confound`).  

in particular, `meat_reg_confound` follows exercise 8.9 in OS4 without the gender issues.
