### ISSUE TITLE
Residual plots - inconsistent x-axis

### ISSUE THREAD

**Issue by debbieyuster** [OpenIntroStat/ims#61]
Following PR #60 I realized this is a more widespread issue. Looks like OIS has residual plots where the x-axis stays the same as in the original plot, showing the explanatory variable. IMS has the x-axis of the residual plot as the predicted y-value of the data. But I believe IMS also recycles some residual plots from OIS which use the alternate x-axis (original explanatory variable). So you will need to come up with a consistent definition (or two types of residual plots with different names?), and make sure all the residual plots and descriptions in each book use whatever definition you agree on for that book (hopefully the same one between OIS and IMS, otherwise it's confusing!). Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
Thanks! We are going to be sticking with predicted vs. residuals for this book and I'll make a note for next edition of OpenIntro Statistics for consistency.

**Comment by nicholasjhorton** [comment]
I'm glad to hear of this decision: I commented in https://github.com/OpenIntroStat/openintro-statistics/issues/45 about how I think that residuals vs. predicted makes most sense (with some discussion of how the different representations are similar with only one predictor and related when there are more than one quantitative predictors).
