### ISSUE TITLE
Chapter 1 - Population parameter, sample statistic not explicitly defined/discussed

### ISSUE THREAD

**Issue by debbieyuster** [OpenIntroStat/ims#62]
Section 1.3.1 (Populations and samples) discusses the difference between populations and samples, and the fact that we use a sample to better understand the population. But the terms "population parameter" and "sample statistic" never appear, until they are used in the Exercises (1.3.6, Exercises 5 & 6).

**Comment by mine-cetinkaya-rundel** [comment]
This is now in [1.3.2](https://openintro-ims.netlify.app/getting-started-with-data.html#parameters-and-statistics)
