### ISSUE TITLE
Figure 3.13 legend unclear/incomplete

### ISSUE THREAD

**Issue by dstoebel** [OpenIntroStat/ims#66]
The figure legend to figure 3.13 says that it is "shown with two least squares line" [sic]. Based on the text in 3.2.2, I think the dashed line is fit by minimizing the absolute value of residuals, not least squares. So perhaps the solid line is the least square line? I can see my students getting confused with this.

PS: Let me know if you'd prefer this kind of feedback in another format, since I'm not an official contributor.

**Comment by mine-cetinkaya-rundel** [comment]
@dstoebel GitHub issues are perfectly fine for feedback!

(And I'll be back actually addressing the issue when I get a chance to re-read the bit, but wanted to leave this quick note for now.)

**Comment by mine-cetinkaya-rundel** [comment]
Thanks @dstoebel, clarified by splitting into two figures and adjusting the narrative accordingly
