### ISSUE TITLE
Simpson's paradox

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims#67]
Mentioned in tutorials but not in book, would be good to mention in Chp 1 and Chp 4.

Use something other than SAT or UCBerkeley examples.

**Comment by hardin47** [comment]
some good simpson's paradox ideas with COVID: https://www.covid-datascience.com/post/israeli-data-how-can-efficacy-vs-severe-disease-be-strong-when-60-of-hospitalized-are-vaccinated

**Comment by mine-cetinkaya-rundel** [comment]
We might also use `openintro::simpsons_paradox_covid`

**Comment by hardin47** [comment]
I did add 4 confounding + SP questions to chatper 4 and 2 to chapter 8.  I didn't use either COVID example.  @mine-cetinkaya-rundel let me know if you want to reopen this issue (or make a new one?) to remind ourselves that we could use COVID for V3.
