### ISSUE TITLE
Review of exercises

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims#68]
Chapter 1

- [x] # 8, section 1.2.6:  smoking habits of UK residents -- the values in the exercise don't match with the table
- [x] # 5 & 6, section 1.3.6: relaxing after work and cats on you tube -- both mention statistic and parameter, but neither term has been used or defined in the text
- [x] # 13, section 1.3.6: haters are gonna hate, study confirms -- part (d) add to the phrase.  "Does the study employ random sampling?  Explain.  How could they have obtained participants?"
- [x] # 16, section 1.3.6: reading the paper -- part (a), rephrase to be "An excerpt from an article titled Risks: Smokers Found More Prone to Dementia is below.  Based on..."  same with (b) "An excerpt from an article titled The School Bully is Sleepy is below. A friend..."
- [x] # 1, section 1.4.2: light and exam performance -- change gender to "wears glasses or not"
- [x] # 3, section 1.4.2: light, noise, and exam performance -- can we somehow communicate to the reader that we know this problem is similar to #1, but actually it is a different problem.  (and again, wears glasses instead of gender)
- [x] # 6, section 1.4.2: exercise and mental health -- awkward phrasing, I think first sentence should be "... on mental health and they propose the following..."
- [x] # 7, section 1.5.2: Stanford open policing -- fix the header on the table (the header should take up two rows)

**Comment by hardin47** [comment]
Chapter 2

There are a good number of problems where I'd love to have the study references.  I'm not sure the best workflow for adding them in...

* #3, section 2.2.7: black lives matter --  the reference does not seem to be showing up
* #4, section 2.2.7: raise taxes -- the reference does not seem to be showing up
* #1, section 2.4.4: side effects of avandia -- the data are in the reference (I think, the footnote doesn't currently work), but i think for this study we should add the full reference.
* #2, section 2.4.4: heart transplants -- the data are in the reference (I think, the footnote doesn't currently work), but i think for this study we should add the full reference.
* #2, section 2.5.2: infant mortality -- the data are in the reference (I think, the footnote doesn't currently work), but i think for this study we should add the full reference.
* #8, section 2.5.2: marathon winners -- the data go to 1999, any chance we can get more updated data?


#9, section 2.1.9: medians and IQRs -- can we add the hint from #8?  "Hint: it may be useful to sketch dot plots of the distributions."

#10, section 2.1.9: histograms and box plots -- add a parenthetical remark "Describe (in words) the distribution..."

#15 and #16, section 2.1.9: distributions and appropriate statistics -- can we add one or two left skewed?  (examples:  age of death, gestation time (is left skewed in `ncbirths`), exam grade on easy test, qualifying jumps for the long jump in the 2012 Olympic games in London.

#2, #3, #4, section 2.2.7: views on immigration, black lives matter, raise taxes -- for the last part in each question we ask "What other variables might explain..."  I'd like to change that wording to "Conjecture other possible variables that might..."

#1, section 2.4.4: side effects of avandia -- Rosiglitaxone and Pioglitazone should be capitalized throughout the problem

#2, section 2.4.4: heart transplants -- we use a "he" pronoun, was it only men? also, can we give a sentence or two mentioning whether or not the treatment was randomized?

#2(a), section 2.4.4: heart transplants -- change the wording to "Does the stacked bar plot indicate that survival is independent of whether or not the patient got a transplant?  Explain your reasoning."

#2(b), section 2.4.4: heart transplants -- instead of "below", label the figure and give it a figure number (or if we can't use a figure number it should be "above" and not "below")

**Comment by hardin47** [comment]
Chapter 3

#1, section 3.1.5: Visualize the residuals -- the word "describe" is used, but it isn't clear to me whether the student is being asked to describe in words or to draw a plot, etc.

#2, section 3.1.5:  Trends in the residuals -- Add "For each plot, describe important ...."

#6, section 3.1.5: Partner's ages and heights -- (1) I'm sort of curious what year the census was?  (2) can we somehow indicate that there is a "first entry" on the form?  i.e., usually the husband.  but just to give the variables a little bit of specificity.

#10, section 3.1.5:  Guess the correlation -- change the title of the exercise from guess to "Transform".  Also, add "Explain." at the end of the problem.

#14, section 3.1.5: Graduate degrees and salaries -- can we make it more clear that the observational unit is "position"  (and not person)?

**Comment by hardin47** [comment]
categorical data on admissions trends due to the pandemic https://www.forbes.com/sites/avivalegatt/2021/01/12/five-college-admissions-trends-for-2021/?sh=5d8498c23d28 

https://www.ivycoach.com/2021-ivy-league-admissions-statistics/

**Comment by mine-cetinkaya-rundel** [comment]
- Light, noise, and exam preference -- Won't mention earlier question with similar context since some students might not do / be assigned all questions in the book.

**Comment by hardin47** [comment]
- [ ] move these from section 2.9 in ISRS to  chp 12
 2.1 Side effects of Avandia, Part I.
 2.2 Heart transplants, Part II.
 2.3 Side effects of Avandia, Part II.
 2.4 Sinusitis and antibiotics, Part II.
 2.6 Is yawning contagious, Part I.
 2.8 Is yawning contagious, Part II.

- [ ] move from 2.9 in ISRS to chp 17
2.9 The Egyptian Revolution.
2.10 Assisted Reproduction.
