### ISSUE TITLE
Feature request: discussion of 1-tailed vs. 2-tailed hypothesis tests

### ISSUE THREAD

**Issue by dstoebel** [OpenIntroStat/ims#75]
As far as I can tell, there is not a specific section of the text that discusses using 1-tailed vs. 2-tailed tests. I always have a few students who struggle with this when I first introduce hypothesis testing, and it would be nice to have a specific piece of text to send them to read. 

I'm not sure if this should go in Chapter 5.1, since that is where hypothesis tests are introduced, or if it is a detail that belongs later.

Thanks!

Dan Stoebel

**Comment by mine-cetinkaya-rundel** [comment]
We do address them in [Section 6.2.1](https://openintro-ims.netlify.app/inference-cat.html#two-prop-errors) however I agree that we should (1) pull that discussion up and (2) make it easier to navigate to. This is in our plans for 1st edition so I'll close this issue for now.
