### ISSUE TITLE
Typo in 4.5

### ISSUE THREAD

**Issue by gregrs-uk** [OpenIntroStat/ims#9]
https://github.com/OpenIntroOrg/randomization-and-simulation/blob/c3d7a2214c1ec5b118e9e5022bdba37ad59deb6c/04/TeX/04-V01.tex#L1190

> Just as we care about the precision of a sample mean, we may care about the precise of the sample standard deviation.

should read

> Just as we care about the precision of a sample mean, we may care about the **precision** of the sample standard deviation.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks, this is fixed now!
